<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:otm="http://xmlns.oracle.com/apps/otm" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.oracle.com/apps/otm/IntXmlService" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" targetNamespace="http://xmlns.oracle.com/apps/otm/IntXmlService">
<wsp:UsingPolicy wssutil:Required="true"/>
<wsp:Policy wssutil:Id="IntXmlService-Policy">
<ns0:SupportingTokens xmlns:ns0="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
<wsp:Policy>
<ns0:UsernameToken ns0:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
<wsp:Policy>
<ns0:WssUsernameToken10/>
</wsp:Policy>
</ns0:UsernameToken>
</wsp:Policy>
</ns0:SupportingTokens>
</wsp:Policy>
<types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import namespace="http://xmlns.oracle.com/apps/otm" schemaLocation="http://hq-otm-d1.trcont.ru:7001/GC3Services/IntXmlService/call?xsd=1"/>
</xsd:schema>
</types>
<message name="process">
<part xmlns:partns="http://xmlns.oracle.com/apps/otm" element="otm:Transmission" name="payload"/>
</message>
<message name="processResponse">
<part xmlns:partns="http://xmlns.oracle.com/apps/otm" element="otm:TransmissionAck" name="result"/>
</message>
<portType name="IntXml">
<operation name="process">
<input message="tns:process"/>
<output message="tns:processResponse"/>
</operation>
</portType>
<binding name="IntXml" type="tns:IntXml">
<wsp:PolicyReference URI="#IntXmlService-Policy"/>
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="process">
<soap:operation soapAction="process" style="document"/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="IntXmlService">
<port binding="tns:IntXml" name="IntXml">
<soap:address location="http://hq-otm-d1.trcont.ru:7001/GC3Services/IntXmlService/call"/>
</port>
</service>
</definitions>