//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trcont.Fss.Service.MMTCService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMTCCalculateTariffParams", Namespace="http://schemas.datacontract.org/2004/07/TranspMan.AppServer.Wcf")]
    [System.SerializableAttribute()]
    public partial class MMTCCalculateTariffParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContParkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DeclaredCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETSNGcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GNGCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsСontTrainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NettoWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WagonOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WagonParkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WagonTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContOwner {
            get {
                return this.ContOwnerField;
            }
            set {
                if ((this.ContOwnerField.Equals(value) != true)) {
                    this.ContOwnerField = value;
                    this.RaisePropertyChanged("ContOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContPark {
            get {
                return this.ContParkField;
            }
            set {
                if ((this.ContParkField.Equals(value) != true)) {
                    this.ContParkField = value;
                    this.RaisePropertyChanged("ContPark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContTypeCode {
            get {
                return this.ContTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContTypeCodeField, value) != true)) {
                    this.ContTypeCodeField = value;
                    this.RaisePropertyChanged("ContTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeclaredCost {
            get {
                return this.DeclaredCostField;
            }
            set {
                if ((this.DeclaredCostField.Equals(value) != true)) {
                    this.DeclaredCostField = value;
                    this.RaisePropertyChanged("DeclaredCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETSNGcode {
            get {
                return this.ETSNGcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ETSNGcodeField, value) != true)) {
                    this.ETSNGcodeField = value;
                    this.RaisePropertyChanged("ETSNGcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPointCode {
            get {
                return this.FromPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPointCodeField, value) != true)) {
                    this.FromPointCodeField = value;
                    this.RaisePropertyChanged("FromPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GNGCode {
            get {
                return this.GNGCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GNGCodeField, value) != true)) {
                    this.GNGCodeField = value;
                    this.RaisePropertyChanged("GNGCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsСontTrain {
            get {
                return this.IsСontTrainField;
            }
            set {
                if ((this.IsСontTrainField.Equals(value) != true)) {
                    this.IsСontTrainField = value;
                    this.RaisePropertyChanged("IsСontTrain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NettoWeight {
            get {
                return this.NettoWeightField;
            }
            set {
                if ((this.NettoWeightField.Equals(value) != true)) {
                    this.NettoWeightField = value;
                    this.RaisePropertyChanged("NettoWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPointCode {
            get {
                return this.ToPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPointCodeField, value) != true)) {
                    this.ToPointCodeField = value;
                    this.RaisePropertyChanged("ToPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalWeight {
            get {
                return this.TotalWeightField;
            }
            set {
                if ((this.TotalWeightField.Equals(value) != true)) {
                    this.TotalWeightField = value;
                    this.RaisePropertyChanged("TotalWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WagonOwner {
            get {
                return this.WagonOwnerField;
            }
            set {
                if ((this.WagonOwnerField.Equals(value) != true)) {
                    this.WagonOwnerField = value;
                    this.RaisePropertyChanged("WagonOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WagonPark {
            get {
                return this.WagonParkField;
            }
            set {
                if ((this.WagonParkField.Equals(value) != true)) {
                    this.WagonParkField = value;
                    this.RaisePropertyChanged("WagonPark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WagonTypeCode {
            get {
                return this.WagonTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WagonTypeCodeField, value) != true)) {
                    this.WagonTypeCodeField = value;
                    this.RaisePropertyChanged("WagonTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMTCCalculateTariffResponse", Namespace="http://schemas.datacontract.org/2004/07/TranspMan.AppServer.Wcf")]
    [System.SerializableAttribute()]
    public partial class MMTCCalculateTariffResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseXmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseXml {
            get {
                return this.ResponseXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseXmlField, value) != true)) {
                    this.ResponseXmlField = value;
                    this.RaisePropertyChanged("ResponseXml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMTCGetRefbookParams", Namespace="http://schemas.datacontract.org/2004/07/TranspMan.AppServer.Wcf")]
    [System.SerializableAttribute()]
    public partial class MMTCGetRefbookParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trcont.Fss.Service.MMTCService.MMTCRefbook RefbookKindField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trcont.Fss.Service.MMTCService.MMTCRefbook RefbookKind {
            get {
                return this.RefbookKindField;
            }
            set {
                if ((this.RefbookKindField.Equals(value) != true)) {
                    this.RefbookKindField = value;
                    this.RaisePropertyChanged("RefbookKind");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMTCRefbook", Namespace="http://schemas.datacontract.org/2004/07/TranspMan.AppServer.Wcf")]
    public enum MMTCRefbook : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlaceType = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Place = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContainerType = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeographicalObject = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailCarFirmOwner = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailCarOwner = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailCarType = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailContainerFirmOwner = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailContainerOwner = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailContainerType = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailEscortType = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailGoodsEtsngCode = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailGoodsGngCode = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RailShippingType = 110,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MMTCGetRefbookResponse", Namespace="http://schemas.datacontract.org/2004/07/TranspMan.AppServer.Wcf")]
    [System.SerializableAttribute()]
    public partial class MMTCGetRefbookResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseXmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseXml {
            get {
                return this.ResponseXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseXmlField, value) != true)) {
                    this.ResponseXmlField = value;
                    this.RaisePropertyChanged("ResponseXml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMTCService.IMMTCService")]
    public interface IMMTCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMMTCService/DoCalculateTariff", ReplyAction="http://tempuri.org/IMMTCService/DoCalculateTariffResponse")]
        Trcont.Fss.Service.MMTCService.DoCalculateTariffResponse DoCalculateTariff(Trcont.Fss.Service.MMTCService.DoCalculateTariffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMMTCService/DoCalculateTariff", ReplyAction="http://tempuri.org/IMMTCService/DoCalculateTariffResponse")]
        System.Threading.Tasks.Task<Trcont.Fss.Service.MMTCService.DoCalculateTariffResponse> DoCalculateTariffAsync(Trcont.Fss.Service.MMTCService.DoCalculateTariffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMMTCService/GetRefbook", ReplyAction="http://tempuri.org/IMMTCService/GetRefbookResponse")]
        Trcont.Fss.Service.MMTCService.GetRefbookResponse GetRefbook(Trcont.Fss.Service.MMTCService.GetRefbookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMMTCService/GetRefbook", ReplyAction="http://tempuri.org/IMMTCService/GetRefbookResponse")]
        System.Threading.Tasks.Task<Trcont.Fss.Service.MMTCService.GetRefbookResponse> GetRefbookAsync(Trcont.Fss.Service.MMTCService.GetRefbookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoCalculateTariff", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoCalculateTariffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Trcont.Fss.Service.MMTCService.MMTCCalculateTariffParams mmtcParams;
        
        public DoCalculateTariffRequest() {
        }
        
        public DoCalculateTariffRequest(Trcont.Fss.Service.MMTCService.MMTCCalculateTariffParams mmtcParams) {
            this.mmtcParams = mmtcParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoCalculateTariffResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoCalculateTariffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Trcont.Fss.Service.MMTCService.MMTCCalculateTariffResponse DoCalculateTariffResult;
        
        public DoCalculateTariffResponse() {
        }
        
        public DoCalculateTariffResponse(Trcont.Fss.Service.MMTCService.MMTCCalculateTariffResponse DoCalculateTariffResult) {
            this.DoCalculateTariffResult = DoCalculateTariffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRefbook", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRefbookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Trcont.Fss.Service.MMTCService.MMTCGetRefbookParams refbookParams;
        
        public GetRefbookRequest() {
        }
        
        public GetRefbookRequest(Trcont.Fss.Service.MMTCService.MMTCGetRefbookParams refbookParams) {
            this.refbookParams = refbookParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRefbookResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRefbookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Trcont.Fss.Service.MMTCService.MMTCGetRefbookResponse GetRefbookResult;
        
        public GetRefbookResponse() {
        }
        
        public GetRefbookResponse(Trcont.Fss.Service.MMTCService.MMTCGetRefbookResponse GetRefbookResult) {
            this.GetRefbookResult = GetRefbookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMMTCServiceChannel : Trcont.Fss.Service.MMTCService.IMMTCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MMTCServiceClient : System.ServiceModel.ClientBase<Trcont.Fss.Service.MMTCService.IMMTCService>, Trcont.Fss.Service.MMTCService.IMMTCService {
        
        public MMTCServiceClient() {
        }
        
        public MMTCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MMTCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMTCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMTCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trcont.Fss.Service.MMTCService.DoCalculateTariffResponse DoCalculateTariff(Trcont.Fss.Service.MMTCService.DoCalculateTariffRequest request) {
            return base.Channel.DoCalculateTariff(request);
        }
        
        public System.Threading.Tasks.Task<Trcont.Fss.Service.MMTCService.DoCalculateTariffResponse> DoCalculateTariffAsync(Trcont.Fss.Service.MMTCService.DoCalculateTariffRequest request) {
            return base.Channel.DoCalculateTariffAsync(request);
        }
        
        public Trcont.Fss.Service.MMTCService.GetRefbookResponse GetRefbook(Trcont.Fss.Service.MMTCService.GetRefbookRequest request) {
            return base.Channel.GetRefbook(request);
        }
        
        public System.Threading.Tasks.Task<Trcont.Fss.Service.MMTCService.GetRefbookResponse> GetRefbookAsync(Trcont.Fss.Service.MMTCService.GetRefbookRequest request) {
            return base.Channel.GetRefbookAsync(request);
        }
    }
}
